### ISSUE TITLE
Error: Unhandled exception in script

### ISSUE THREAD

**Issue by Kinasa0096** [adenzu/Manga-Panel-Extractor#16]
Version 2.0 does not start, displaying the error "Unhandled exception in script.". Details:

Failed to execute script 'main' due to unhandled exception: 'cp932' codec can't encode character 'u2705' in position 132: illegal multibyte sequence

```
Traceback (most recent call last):
  File "logging\__init__.py", line 1103, in emit
UnicodeEncodeError: 'cp932' codec can't encode character '\u2705' in position 46: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "gui\window.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "gui\extractor.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "image_processing\panel.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "image_processing\model.py", line 13, in <module>
  File "torch\hub.py", line 647, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "torch\hub.py", line 676, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\rozenkristall/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 135, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "C:\Users\rozenkristall/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 54, in _create
    from models.common import AutoShape, DetectMultiBackend
  File "C:\Users\rozenkristall/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 27, in <module>
    import ultralytics
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "ultralytics\__init__.py", line 11, in <module>
    from ultralytics.models import NAS, RTDETR, SAM, YOLO, FastSAM, YOLOWorld
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "ultralytics\models\__init__.py", line 3, in <module>
    from .fastsam import FastSAM
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "ultralytics\models\fastsam\__init__.py", line 3, in <module>
    from .model import FastSAM
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "ultralytics\models\fastsam\model.py", line 5, in <module>
    from ultralytics.engine.model import Model
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "ultralytics\engine\model.py", line 11, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "ultralytics\cfg\__init__.py", line 12, in <module>
    from ultralytics.utils import (
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "ultralytics\utils\__init__.py", line 1287, in <module>
    SETTINGS = SettingsManager()  # initialize settings
  File "ultralytics\utils\__init__.py", line 1217, in __init__
    LOGGER.info(f"Creating new Ultralytics Settings v{version} file ✅ {self.help_msg}")
  File "logging\__init__.py", line 1477, in info
  File "logging\__init__.py", line 1624, in _log
  File "logging\__init__.py", line 1634, in handle
  File "logging\__init__.py", line 1696, in callHandlers
  File "logging\__init__.py", line 968, in handle
  File "logging\__init__.py", line 1108, in emit
  File "logging\__init__.py", line 1031, in handleError
  File "traceback.py", line 206, in print_stack
  File "traceback.py", line 25, in print_list
UnicodeEncodeError: 'cp932' codec can't encode character '\u2705' in position 132: illegal multibyte sequence
```
<img width="301" alt="22 11 2024_12 18 52_explorer_aMX_8997" src="https://github.com/user-attachments/assets/7a31f38a-6359-4458-b799-b377c9f140ee">

**Comment by adenzu** [comment]
Thanks for creating an issue for this! I will be looking into this error really soon.
